### ISSUE TITLE
notificationReceivedBackground didn't fire on iOS

### ISSUE THREAD

**Issue by danqing-jin** [wix/react-native-notifications#101]
Thanks wix for the great work. I'm using the latest react-native-notifications and react-native 0.42.3 and iOS 10.3.3. After I put my app to background, I sent a push notification to my app. The notification showed in the notification center. But the notificationReceivedBackground callback function is not called. Did anyone had this callback called successfully?

**Comment by danqing-jin** [comment]
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW57

Based on Apple's comment, it seems that application:didReceiveRemoteNotification:fetchCompletionHandler: is used to handle this event. In the iOS push notification implementation of react native, I saw this handler declared. But In react-native-notifications, I did not see it. Anyone has ideas how to add this to react-native-notifications?

**Comment by ricms93** [comment]
I'm having the same problem, everything works as expected except the notificationReceivedBackground event.

**Comment by ricms93** [comment]
Any update on this issue???

**Comment by lidanh** [comment]
We're working on prioritizing the issues and will provide solutions soon. sorry for the inconvenience.

**Comment by mrdezzods** [comment]
any news?

**Comment by bdrobinson** [comment]
I'm pretty sure this has now been fixed, so any issues you face are not a problem with the library, but rather the nature of background notifications on iOS. This has been confusing me for the past few hours so I'll post a quick summary of what I learned:

I think the background notification handler only triggers for a given APNs message if:
1. "Background modes > Remote notifications" capability is enabled in XCode.
2. The APNs payload on a given message contains "content-available: 1"

One thing I didn't realise about iOS is that most APNs notifications should *not* be handled by your app while it's in the background. The "content-available: 1" setting lets you opt into this – this will then cause a notification to wake the app from the background, handle the notification (ie, make a network request, or cache something to the disk), and then go back to sleep.

However, Apple say that you should only send ~3 of these per hour so probably shouldn't be used for most notifications.

So basically, you probably shouldn't expect the background notification handler to fire on iOS if you haven't explicitly opted into it. And you probably shouldn't opt into it for notifications like "person x sent you a message" – it sounds to me like background notifications are more designed for content browsing apps (eg, BBC News, Spotify) to periodically make sure their cache is up to date to ensure slick UX.

In one of the below docs, Apple even says that if you send too many of these messages they will throttle them to save battery life (otherwise, if your server sent a message like this every minute then your app would keep waking from background) which would mean you lost messages altogether (which would be bad!).

However this is just my understanding from the docs and some brief experiments – I'm not an expert by any stretch, so read the docs for yourself and let me know if I've got something wrong.

See <https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW8> and <https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html> for more info.
