### ISSUE TITLE
NotificationsIOS event not working

### ISSUE THREAD

**Issue by vink1987** [wix/react-native-notifications#239]
I am making local notifications on IOS device and binding 'notificationOpened' to make sure that I do the needful when open the notification status bas. But this event is not working. Please help me out on this ASAP.

**Comment by a-golovanov** [comment]
TLTR;
Call `NotificationsIOS.consumeBackgroundQueue()` after subscribing to events and requesting permissions, for details see https://github.com/wix/react-native-notifications/blob/master/docs/notificationsEvents.md#background-queue-important---please-read

Full explanation:
The notification module is loaded and initialized lazily when JS calls an exposed method of the module. Calling `addEventListener` doesn't do the trick because it doesn't belong to the module, it implemented by standard `DeviceEventEmitter` instead, but calling either `NotificationsIOS.requestPermissions()` or `NotificationsIOS.consumeBackgroundQueue()` does. Besides, calling `NotificationsIOS.consumeBackgroundQueue()` is required to pick up events/actions that happend while app was closed.

**Comment by a-golovanov** [comment]
@vink1987 
Sorry, I misunderstood your original question. Maybe your problem is similar to https://github.com/wix/react-native-notifications/issues/203, for solution see the second comment from @axlalvaro.
