### ISSUE TITLE
Can someone show me a RNN and RNNotifications example please?

### ISSUE THREAD

**Issue by lfa9603** [wix/react-native-notifications#283]
I am currently trying to integrate react-native-notifications with react-native-navigation and even though I read the wiki about it I am still finding it hard to understand how to do so, for example: where do I need to put the code needed for the subscription (https://github.com/wix/react-native-notifications/blob/master/docs/subscription.md)? Can someone please show me an example using RNN (preferably version 1 if possible) together with RNNotifications? Thanks

**Comment by moshekagan** [comment]
Hi @lfa9603, this repo including an example. You can find it here https://github.com/wix/react-native-notifications/tree/master/example. 
Hopefully, it will help you.

**Comment by rickgonzalez** [comment]
The question was related to the use of React Native Navigation and React Native Notifications.  There's specific instructions about integrating these libraries.  The example pointed to has a basic build and doesn't include RNN.  It appears that the RNN instructions are outdated as there are expected libraries that no longer exist in the latest builds of RNN.  Does anyone have a more recent integration example they can post?

**Comment by diegolmello** [comment]
@lfa9603 @rickgonzalez Here's an example https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by sorin-f-wiredelta** [comment]
@diegolmello doesn't seem to be relevant since we are talking about react-native-navigation V2 and not react-navigation (which is completely different) as specified in the package.json for the project you linked. I can see in one of the commits that it was changed to react-navigation. Was it running before with RNNv2? and if so, could you point me to the respective commit? and may I ask what was the reason for this?

**Comment by diegolmello** [comment]
@sorin-f-wiredelta I'm sorry about that. We migrated 3 days ago.
Until [this commit](https://github.com/RocketChat/Rocket.Chat.ReactNative/commit/eb4b1553bf4bed65cce9ca201652143e8f778943) we were using RNN with react-native-notifications.
We switched to react-navigation because it's too hard to maintain an app with RNN.
