### ISSUE TITLE
[Android] Could not convert class android.os.UserHandle

### ISSUE THREAD

**Issue by AugustoAleGon** [wix/react-native-notifications#287]
Currently I was able to set up `react-native-notifications` with `react-native-navigation`. The first 5 minutes I can receive push notifications from the firebase console, but after 5 minutes I can't receive any other update from the server. If I close the app and got a message:

![screenshot-1549251517068](https://user-images.githubusercontent.com/14319083/52189158-f06a7680-2804-11e9-8631-28927cd6e59d.jpg)

Thanks in advance.

**Comment by Monish-Coddle** [comment]
Hi,

Even i am getting the same error

> Fatal Exception: java.lang.IllegalArgumentException: Could not convert class android.os.UserHandle
       at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:302)
       at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1063)
       at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
       at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
       at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:201)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:764)


The issue is happening on certain devices, following are the list

- Mi Note 10 Pro (Android 9)
- Redmi 5 (Android 8.1.0)
- POCO F1 (Android 10)
- CPH1715 (Android 6.0)
- Redmi Note 8 pro (Android 9)
- Redmi Note 5 Pro (Android 9)
- Redmi 5A (Android 8.1.0)
- F11 Pro (Android 9)

I am using following dependencies in my project

`"@react-native-community/async-storage": "^1.6.2",
"@react-native-community/cli-platform-android": "^2.9.0",
"@react-native-community/netinfo": "^5.2.0",
"moment": "^2.24.0",
"react": "16.9.0",
"react-native": "0.61.4",
"react-native-background-timer": "^2.1.1",
"react-native-device-info": "^5.4.0",
"react-native-elements": "^1.2.7",
"react-native-firebase": "~5.5.6",
"react-native-gesture-handler": "^1.5.0",
"react-native-image-crop-picker": "^0.26.1",
"react-native-image-zoom-viewer": "^2.2.27",
"react-native-intercom": "13.1.0",
"react-native-keyboard-aware-scrollview": "^2.1.0",
"react-native-linear-gradient": "^2.5.6",
"react-native-material-textfield": "^0.16.1",
"react-native-modal": "^11.5.3",
"react-native-progress": "^4.0.2",
"react-native-realm": "^0.1.2",
"react-native-reanimated": "^1.4.0",
"react-native-screens": "^1.0.0-alpha.23",
"react-native-tab-view": "^2.11.0",
"react-native-table-component": "^1.2.1",
"react-native-vector-icons": "^6.6.0",
"react-native-version-number": "^0.3.6",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "^2.3.3",
"react-navigation-stack": "^1.10.3",
"react-navigation-tabs": "^2.5.6",
"realm": "^3.3.0"`

As well as i have used following permission in my android application

`<uses-permission android:name="android.permission.BIND_NOTIFICATION_LISTENER_SERVICE" />`

I have read couple of places that this is a know issue on Xiaomi devices . I followed [this link](https://www.reddit.com/r/MarvelStrikeForce/comments/c5kh22/not_open_after_update_android/)  and tried to install and uninstall the application but still the same issue.

Let me know if someone has any insight on how to effectively tackle this issue.

**Comment by jagnesh** [comment]
facing same issue.. Please share solution for this.

**Comment by sniperosx** [comment]
Still facing the same issue about one year later. 
Only appearing on a Xiaomi devices (Redmi 7). 

Has anyone a workaround to get this running?

**Comment by Monish-Coddle** [comment]
Hi @sniperosx 

I was getting the error while using following code

`@Nullable
@Override
protected Bundle getLaunchOptions() {
    Bundle bundle = getIntent().getExtras();
    if(bundle != null) {
        bundle.putString("some_key", bundle.getString("some_key"));
    }
    return bundle;
}`

After trying different option , following code made it working for me

`@Nullable
@Override
protected Bundle getLaunchOptions() {
    Bundle bundle = new Bundle();
    bundle.putString("default_key", "DEFAULT");
    if(getIntent().getExtras() != null) {
        Bundle notificationBundle = getIntent().getExtras();
        bundle.putString("some_key", notificationBundle.getString("some_key"));
    }
    return bundle;
}`

Simply said, having some default key value pair in the bundle all the time did the trick for me.

**Comment by deepakv-z14** [comment]
any fix for this? we are still facing this crash on 
POCO X4 Pro 5G device
