### ISSUE TITLE
Android Build is Crashing

### ISSUE THREAD

**Issue by codoffer** [wix/react-native-notifications#328]
I am getting an error with logcat 

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf"

Below error with build process

 D8: Type `com.google.android.gms.common.internal.safeparcel.zzd` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.GeofencingRequest.writeToParcel(android.os.Parcel, int)`

build.gradle

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "11.0.0"
        firebaseVersion="11.0.0"
    }

**Comment by akhilsanker** [comment]
Same issue here. App is crashing on start.

**Comment by khjde1207** [comment]
+1

**Comment by HoangTrung** [comment]
+1

**Comment by yogevbd** [comment]
Fixed in `2.0.3`. You can easily migrate using the instructions in our [changelog file](https://github.com/wix/react-native-notifications/blob/master/CHANGELOG.md)

Follow our updated installation guide in order to fix this issue [installation guide](https://github.com/wix/react-native-notifications/blob/master/docs/installation.md)
