### ISSUE TITLE
How do we consume background notifications?

### ISSUE THREAD

**Issue by sanjaypojo** [wix/react-native-notifications#365]
The updated documentation has removed `notificationReceivedBackground`. Is there any way to consume the background queue in the new version?

**Comment by yogevbd** [comment]
Can you explain exactly what you try to achieve? It was removed because in both iOS and Android the app doesn't get notified on notifications received when the app is in background.
If you want the app to wake and handle the notification it is possible but the payload sent from the server should look different according to the specific platform.

**Comment by sanjaypojo** [comment]
Thanks for the quick response! We’re looking to send a time-sensitive data push that updates the screen. However, it’s possible that the app goes into background before the push arrives. When the user reopens the app, we want to make sure the push notification is processed and the screen updates. What’s the best way to achieve this?

**Comment by calcazar** [comment]
@yogevbd I can confirm that that you can receive and perform app actions using that nootificationBackgroundReceived event.

Before updating to the latest version, our app utilized the event to hit one of our services once an individual notification arrived. This event was being called with the app closed, in the background or even swiped away on iOS. After updating to the latest version, this no longer works. 

As a side effect, removing consumeBackgroundQueue() also messed things up for us because we used that function to execute various tasks when the app was opened after it received a background notification.

So the way it would work is:

App is closed, swiped away, unopen
Push notification was sent to the app
App would open in the background
App would call our Ping Pong service to confirm the push notification was received
-----
User opens their phone and sees they have a notification
User Swipes away at notification
User then opens the app (not taping the notification)
consumeBackgroundQueue was executed
Service call was made based on the alerts received to retrieve additional data


Now I'm stuck at the moment how to get the app to function when the app is closed/swiped away. The functionality I see is:

App is closed, swiped away, unopen
Push notification was sent to the app
App would open in the background
<END>
A second push notification is sent out
App would call our Ping Pong service to confirm the second push notification was received (it skips the first)

**Comment by bdrobinson** [comment]
@sanjaypojo my method for solving this was instead to create an [UNNotificationServiceExtension App Extension](https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension) which intercepts every APS message and writes it to a simple JSON store using `NSUserDefaults`. Then when the app is next opened, the app can pops messages out of the store and you can then use messages in JS-land.

It took a bit of setting up but I think that's the "proper" way to do it, as it means your app doesn't need to launch/be alive every time a push notification arrives, as the (very lightweight) app extension takes care of it.

There's some gotchas with it (eg your APS messages need `mutable-content: 1` set) but it's working really well for us.

**Comment by calcazar** [comment]
@bdrobinson can you share a quick example for us who aren't familiar with Objective C :)

**Comment by sanjaypojo** [comment]
@bdrobinson awesome, thanks for sharing! Will check it out. +1 for an example if you have one :)

**Comment by bdrobinson** [comment]
There's not really a quick snippet of code I can share, but if you just google around `UNNotificationServiceExtension` you should find a few tutorials – there's nothing specific to react native around the way it's written. The interesting stuff will happen in your implementation of `didReceiveNotificationRequest` – you can inspect the push message contents and write whatever you want to some storage that your main app will be able to access (app extensions are sandboxed from main apps). I used `NSUserDefaults` which is possibly a bit hacky but it's worked well for us so whatever.

Then you just need to be able to read `NSUserDefaults` from JavaScript once the user does launch/re-open your app. I wrote my own native module bindings to do this but it looks like I could have just used this instead <https://facebook.github.io/react-native/docs/settings>

So yeah you need to write some Obj-C/Swift, but it's mostly copy+pasting so not too bad.

**Comment by vishalnarkhede** [comment]
@calcazar did you manage to build this thing?

**Comment by calcazar** [comment]
@vishalnarkhede I went a different direction, I didn't write the extension mentioned above
