### ISSUE TITLE
Missing MyIntentUtils in Android: Layout Customization

### ISSUE THREAD

**Issue by lmrarturo** [wix/react-native-notifications#387]
Hello,

I'm creating custom notifications supporting me in your [Wiki documentation](https://github.com/wix/react-native-notifications/wiki/Android:-Layout-Customization)

**My code of Custom Push-Notification Class**
`public class MyPushNotification extends PushNotification {

    public MyPushNotification(Context context, Bundle bundle, AppLifecycleFacade appLifecycleFacade, AppLaunchHelper appLaunchHelper, JsIOHelper jsIoHelper) {
        super(context, bundle, appLifecycleFacade, new AppLaunchHelper(), new JsIOHelper());
    }

    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
    @RequiresApi(api = Build.VERSION_CODES.KITKAT_WATCH)
    @Override
    protected Notification.Builder getNotificationBuilder(PendingIntent intent) {
        final Resources resources = mContext.getResources();

        // First, get a builder initialized with defaults from the core class.
        final Notification.Builder builder = super.getNotificationBuilder(intent);

        // Set our custom overrides --

        // Enable 'extended' layout (extends on down-stroke gesture):
        final Notification.BigTextStyle extendedNotificationStyle =
                new Notification.BigTextStyle()
                        .bigText(mNotificationProps.getBody()); // "4:15 - 5:15 PM\nBig Conference Room"
        builder.setStyle(extendedNotificationStyle);

        builder.setPriority(PRIORITY_HIGH);

        Set custom-action icon.
        builder.setSmallIcon(R.drawable.meeting_icon)
                .setColor(resources.getColor(R.color.notification_bkg_color)); // Blue-ish
        

        // Add 'email guests' action.
        Notification.Action emailGuestsAction = new Notification.Action(
                R.drawable.action_email_guests,
                resources.getString(R.string.action_email_guests),
                MyIntentUtils.getComposeEmailIntent(mNotificationProps.asBundle().getStringArrayList("invited")));
        builder.addAction(emailGuestsAction);

        return builder;
    }
}`

**Problem**
I can't find the "MyIntentUtils" and I don't know if I have to create it (and how) or if you forgot to share that part of the code in the wiki documentation.

I'll appreciate if you can help me with this. It is the only thing where I'm stuck.

**Past Issue asking the same question. #119**

Thank you!

**Comment by pepesrz91** [comment]
Same thing here. 

We are able to use native notifications but we just cant figure out how to pass the notification object to react native so that we can use the same functions as the ones you guys implemented for iOS. Just like the example below.


```javascript

constructor() {
  NotificationsIOS.addEventListener('pushKitRegistered', this.onPushKitRegistered.bind(this));
  NotificationsIOS.addEventListener('pushKitNotificationReceived', this.onPushKitNotificationReceived.bind(this));
  NotificationsIOS.registerPushKit();
}

onPushKitRegistered(deviceToken) {
	console.log("PushKit Token Received: " + deviceToken);
}

onPushKitNotificationReceived(notification) {
    console.log('PushKit notification Received: ' + JSON.stringify(notification));
}

componentWillUnmount() {
	// Don't forget to remove the event listeners to prevent memory leaks!
	NotificationsIOS.removeEventListener('pushKitRegistered', onPushKitRegistered(this));
}

```

This is what you guys have for android:

```javascript
import {NotificationsAndroid} from 'react-native-notifications';

// On Android, we allow for only one (global) listener per each event type.
NotificationsAndroid.setNotificationReceivedListener((notification) => {
	console.log("Notification received on device in background or foreground", notification.getData());
});
NotificationsAndroid.setNotificationReceivedInForegroundListener((notification) => {
	console.log("Notification received on device in foreground", notification.getData());
});
NotificationsAndroid.setNotificationOpenedListener((notification) => {
	console.log("Notification opened by device user", notification.getData());
});
```

The question is, how can we link a custom notification (notification with actions) in Android to the methods above so that we can get the notification object and do the corresponding functionalities? 

If you guys could show the way or share some code snippet it would be awesome. Just want to say that the library is amazing. Thank you beforehand for the help and for the awesome job!

**Comment by pepesrz91** [comment]
@lmrarturo just wondering if you had any advance with this topic, or any of you guys. Thanks for the help!

**Comment by pepesrz91** [comment]
@lmrarturo and Wix team.. Still haven't achieve a good solutions for this topic. I don't kow if you guys have any updates. Thanks!

**Comment by d4vidi** [comment]
@pepesrz91 @lmrarturo I'm not sure what you mean by this. `MyIntentUtils` is a theoretical class, mentioned inside a theoretical block which you need to adjust so as to make it fit for you app. In the wiki doc the code merely describes how to achieve something like the result in the preliminary screenshot, nothing more. It is up to you to create the necessary tools and logic since it's very tightly coupled with your product.

**Comment by pepesrz91** [comment]
Hey @d4vidi!

Thanks a lot for the response.

We understand that ```MyItentUtils``` is a theoretical class and we are able to implement the proper logic and functionality in Android for the notifications, but it doesn't work that well for us because our notification system interacts with our application state which we handle by using Redux.  

So our main issue is that we don't know and understand well how can we connect our own notification categories, created natively android,  to the functions you guys have already implemented as:

```javascript
onNotificationReceivedForeground(notification, completion) { ... };
onNotificationOpened(notification, completion, action) {...}; 
```
So that's why we related this issue to missing ```MyIntentUtils``` because we don't know exactly if we can actually connect, sort of speak, our own notifications categories and actions to the functions implemented that you guys implemented to catch notifications in React Native. And if it is possible, we are totally lost on how to implement it correctly.  

If you guys could point us to the right direction it would be awesome. Thanks for the help!

**Comment by d4vidi** [comment]
@pepesrz91 you're not suppose to catch notifications in RN at this point. The native handling code you're referring to simply posts a notification in the device's notification center, nothing more. You _do_ need to bundle an intent (over a `PendingIntent`) but again, that's product-specific.
