### ISSUE TITLE
consumeBackgroundQueue not always firing

### ISSUE THREAD

**Issue by EmilScherdin** [wix/react-native-notifications#5]
Hi!

First of, great job with this package! 😄

I'm trying to use Interactive notifications to postpone tasks in my app. But when i press an action it does not always fire the ´consumeBackgroundQueue´ function. I'm calling it in the constructor of my app component, just like in the example:

``` javascript
constructor(props) {
    super(props);

    NotificationsIOS.addEventListener('remoteNotificationsRegistered', token => {
      Store.dispatch(updateUser({ pushToken: token }));
    });
    NotificationsIOS.addEventListener('notificationReceivedForeground', this.onLocalNotification.bind(this));
    NotificationsIOS.addEventListener('notificationReceivedBackground', () => console.log('background notification received'));
    NotificationsIOS.addEventListener('notificationOpened', this.onNotification.bind(this));

    NotificationsIOS.requestPermissions([cat]);
    NotificationsIOS.consumeBackgroundQueue();
  }
```

I have found a pattern. When i only press an action on a notification and the app is closed it's not firing but i i have multiple notification after each other and press on actions for 2-3 of them, it's firing.

Can i call the function some where else to get it to run every time?

**Comment by lidanh** [comment]
Hi Emil!

I couldn't reproduce your bug, but I'll describe how it works and I hope it will help us to investigate your issue together.
When the app is closed and you press on an action, the cold start takes 2-3 seconds, until the JS bridge is up and able to handle the action.  If I try to call the action handler once the button is pressed, it won't be handled since the JS bridge is still down.

Instead, I store the actions in a **native** background queue, until the JS bridge is up and ready to handle them. when is it ready?  once you call to `NotificationsIOS.consumeBackgroundQueue();
`

https://github.com/wix/react-native-notifications/blob/6497ee023b9baf872a2df7d5f4051d9c8dccedf8/RNNotifications/RNNotifications.m#L463

**Comment by EmilScherdin** [comment]
Thanks for the reply and sorry for my super delayed answer.

I think I have tracked the problem down to the RN fetch that's get a Timeout on my request. 
I have no idea why but it only happens when the app is cold started. All the notification actions works as expected after that! 

Have you successfully tested with doing requests when pressing a notification action?
Or if you have some clever solution that i could test?

Trying to get some error logs but no success so far. Only have this:
![timeout](https://cloud.githubusercontent.com/assets/6998447/19284552/a8e83dae-8ff6-11e6-88a8-268f7da38782.png)

**Comment by EmilScherdin** [comment]
@lidanh ping

**Comment by EmilScherdin** [comment]
Okey so i solved my problem by being able to remove the request.

But I was thinking maybe if you call the `completed();` before the request is done. It doesn't look like it should matter but it may be worth a shot to wrap it in a promise? It may help someone. What do you think @lidanh
