### ISSUE TITLE
Outdated Gist - ReactNativeNavigation V6 integration

### ISSUE THREAD

**Issue by mkharibalaji** [wix/react-native-notifications#532]
Hi Team,
         Any idea of how to integrate latest ReactNativeNavigation V6 with React Native Notifications as the Android Facade Gist is outdated.

Thanks

**Comment by itsam** [comment]
Hi, any news on this? 
Thank you in advance

**Comment by itsam** [comment]
That's a MAJOR issue and it shouldn't be staled.
Documentation on linking RNN and react native notifications is a MUST have.
Thank you!

**Comment by mkharibalaji** [comment]
@BenJeau - Please update the latest doc to integrate React Native Navigation V6 which is more critical for android and stuck for a few months now.if you could help it would be great.

**Comment by BenJeau** [comment]
Ok, I'll try to look into it tomorrow/today. When I was testing out this library with `react-native-navigation`, I was not able to get it working, seemed to be an error with Firebase and needed to be setup, even if the docs suggests it's optional. I will try with Firebase and I'll give you an update

**Comment by mkharibalaji** [comment]
Thanks a lot @BenJeau :+1:

**Comment by itsam** [comment]
Thanks in advance! I am sure a lot of people are waiting for this :)

**Comment by BenJeau** [comment]
When I tried to use `react-native-navigation` and `react-native-notifications`, everything worked fairly well. Here's a short guide showing what I did (this works for Android, not sure for iOS since I don't have a mac). Autolinking is used to link `react-native-notifications`. Please let me know if this works for you or not

<hr/>

### Created a new app

Ex: `npx react-native init rn-notifications`

### Add `react-native-notifications`

Ex: `yarn add react-native-notifications`

Then I ran the app, but I got this error

```logs
04-28 09:38:34.952  9989 10037 E AndroidRuntime: FATAL EXCEPTION: IntentService[FcmInstanceIdRefreshHandlerService]
04-28 09:38:34.952  9989 10037 E AndroidRuntime: Process: com.rnn, PID: 9989
04-28 09:38:34.952  9989 10037 E AndroidRuntime: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.rnn. Make sure to call FirebaseApp.initializeApp(Context) first.
04-28 09:38:34.952  9989 10037 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.1:219)
04-28 09:38:34.952  9989 10037 E AndroidRuntime: 	at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:1)
04-28 09:38:34.952  9989 10037 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmToken.refreshToken(FcmToken.java:78)
04-28 09:38:34.952  9989 10037 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmToken.onAppReady(FcmToken.java:68)
04-28 09:38:34.952  9989 10037 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmInstanceIdRefreshHandlerService.onHandleIntent(FcmInstanceIdRefreshHandlerService.java:23)
04-28 09:38:34.952  9989 10037 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
04-28 09:38:34.952  9989 10037 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-28 09:38:34.952  9989 10037 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-28 09:38:34.952  9989 10037 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

It seems like firebase is needed, so you need to do the following

1. Add to ./android/build.gradle

```diff
buildscript {
  ...
  dependencies {
    ...
+    classpath 'com.google.gms:google-services:4.3.3'
  }
}
```

2. Add to ./android/app/build.gradle

```diff
...
+ apply plugin: 'com.google.gms.google-services'
```

3. Add the `google-service.json` file from your [Firebase project](https://console.firebase.google.com/) to ./android/app

Everything should compile fine at this point.

### Add `react-native-navigation`

Ex: `yarn add react-native-navigation`

### Link `react-native-navigation` files

Ex: `npx react-native link react-native-navigation`

Everything should work, if you get a `com.android.builder.dexing.DexArchiveMergerException`, add the following to the ./android/app/build.gradle

```diff
android {
  ...
  defaultConfig {
    ...
+   multiDexEnabled true
  }
}
```

**Comment by BenJeau** [comment]
You don't need to do a lot of the things from what is mentioned in docs, it seems really outdated. If this works for you guys, I'll update the docs

**Comment by mkharibalaji** [comment]
@BenJeau - Thanks for your efforts.I was able to make it to work last weekend but the issue was when i traverse to different screens,i get two or more of the same  notifications called because of the screen activity lifecycle issue . I am using React Native 0.61.5 and with the same stuff that you mentioned,so that's where i was stuck fundamentally getting many of the same notifications again and again.

Do you mean that lifecycle activity is not an issue for RNN V6 ?

**Comment by BenJeau** [comment]
Oh, I misunderstood you. I'll be honest, I haven't played a lot with this library and just found it, but right now if I deliver notifications via Firebase, locally and if I create a custom notification layout [described here](https://github.com/wix/react-native-notifications/wiki/Android:-Layout-Customization), I don't get multiple notifications.

I only seem to get multiple notifications if I post local notifications in any screens without an `id` specified (which makes sense since they mounted/unmounted with rn-navigation), they should have an, I think. If this is the lifecycle activity issue, I suppose it's still present.
