### ISSUE TITLE
Error setting up in iOS (lib/dist/index.js doesn't exist)

### ISSUE THREAD

**Issue by AlexD10S** [wix/react-native-notifications#557]
The library works perfectly on Android, but in iOS when add the line:

`pod 'react-native-notifications', :podspec => '../node_modules/react-native-notifications/react-native-notifications.podspec'`

on the Podfile, install it and run the app, it crash because is unable to find the file lib/dist/index.js

See the full error:

`Metro Bundler has encountered an error: While trying to resolve module `react-native-notifications` from file `whatever`, the package `/project/ios/Pods/react-native-notifications/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/project/ios/Pods/react-native-notifications/lib/dist/index.js`. Indeed, none of these files exist`

The version is installing is: Installing react-native-notifications (3.1.4)

**Comment by StijnCoolen** [comment]
@AlexD10S try this: `pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'`, it worked for me.

**Comment by AlexD10S** [comment]
Thanks, doing this is not crashing.
However, the handling methods of notifications: registerNotificationReceivedForeground, registerNotificationReceivedBackground... of the  library are not working when receive a notification

**Comment by loga4** [comment]
the same 

this not working for me:
https://github.com/wix/react-native-notifications/issues/557#issuecomment-610425746

**Comment by ciprian-iacob** [comment]
I'm getting the same issue on `react-native 0.62.2` and `react-native-notifications: 3.1.4`. Any ideas on how this could be fixed?

**Comment by loga4** [comment]
@ciprian-iacob i have the same issue, when i try to install as a Pod file. And i try to install via Pod, because local notification are not working, but there was another problem: [rn-firebase problem](https://github.com/invertase/react-native-firebase/issues/3367#issuecomment-611546923) 

so if you using a `react-native-firebase` for remote notifications and `react-native-notification` for local, try to install it without Podfile and install react-native-notification@6.4.1-alpha.0

**Comment by JulioC** [comment]
> `Metro Bundler has encountered an error: While trying to resolve module `react-native-notifications`from file`whatever`, the package `/project/ios/Pods/react-native-notifications/package.json` was successfully found. However, this package itself specifies a`main` module field that could not be resolved (`/project/ios/Pods/react-native-notifications/lib/dist/index.js`. Indeed, none of these files exist`

The reason this happens is because the .podspec file includes package.json file, so it gets copied into `ios/Pods/react-native-notification`. React-native Metro bundler finds that package.json file and uses it instead of the proper file (which is still under `node_modules`).

**The solution for this specific problem is to delte the file `ios/Pods/react-native-notifications/package.json`.**

This will raise another issue: the js code is looking for a dependency called ReactNativeNotifications, but the .podspec registers the package as react-native-notifications. The easier way is to change the podspec file to match the native module. I'm not sure about the implications of doing that when autolinking though.

If possible, the library could ship two podspecs: the current one for auto-linking; and an alternative for manual link with the native name ReactNativeNotifications.podspec

--- 

Workaround while the library is not fixed:

Use [patch-package](https://www.npmjs.com/package/patch-package) to change the podspec file in node_module so it doesn't include package.json in the pod and also register the proper name.

After installing patch-package and adding it as postinstall, save this as patch file in `patches/react-native-notifications+3.1.4.patch`:

```patch
diff --git a/node_modules/react-native-notifications/react-native-notifications.podspec b/node_modules/react-native-notifications/react-native-notifications.podspec
index c8e4e78..6db6a69 100644
--- a/node_modules/react-native-notifications/react-native-notifications.podspec
+++ b/node_modules/react-native-notifications/react-native-notifications.podspec
@@ -3,7 +3,7 @@ require 'json'
 package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
 
 Pod::Spec.new do |s|
-  s.name           = 'react-native-notifications'
+  s.name           = 'ReactNativeNotifications'
   s.version        = package['version']
   s.summary        = package['description']
   s.description    = package['description']
@@ -15,7 +15,7 @@ Pod::Spec.new do |s|
   s.requires_arc   = true
   s.platform       = :ios, '8.0'
 
-  s.preserve_paths = 'LICENSE', 'README.md', 'package.json', 'notification.ios.js', 'notification.android.js', 'index.android.js', 'index.ios.js'
+  s.preserve_paths = 'LICENSE', 'README.md', 'notification.ios.js', 'notification.android.js', 'index.android.js', 'index.ios.js'
   s.source_files   = 'lib/ios/*.{h,m}'
 
   s.dependency 'React'
```

Change `ios/Podfile` entry to:

```
  pod 'ReactNativeNotifications', :podspec => '../node_modules/react-native-notifications/react-native-notifications.podspec'
```

* Run `yarn install` and `cd ios && pod install`

**Comment by JulioC** [comment]
Any updates on this?

**Comment by hunterlong** [comment]
+1 I'm also getting this error.

**Comment by srshah19** [comment]
+1. Any updates on this?

**Comment by gypsicoder** [comment]
+1 Any updates on this?

**Comment by hiennguyen92** [comment]
+1 Any updates on this?

**Comment by haolei** [comment]
> @AlexD10S try this: `pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'`, it worked for me.

thanks, It works

**Comment by kostiantyn-solianyk** [comment]
`pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'` it doesn't work, any updates?

**Comment by MrVann** [comment]
> > `Metro Bundler has encountered an error: While trying to resolve module `react-native-notifications`from file`whatever`, the package `/project/ios/Pods/react-native-notifications/package.json` was successfully found. However, this package itself specifies a`main` module field that could not be resolved (`/project/ios/Pods/react-native-notifications/lib/dist/index.js`. Indeed, none of these files exist`
> 
> The reason this happens is because the .podspec file includes package.json file, so it gets copied into `ios/Pods/react-native-notification`. React-native Metro bundler finds that package.json file and uses it instead of the proper file (which is still under `node_modules`).
> 
> **The solution for this specific problem is to delte the file `ios/Pods/react-native-notifications/package.json`.**
> 
> This will raise another issue: the js code is looking for a dependency called ReactNativeNotifications, but the .podspec registers the package as react-native-notifications. The easier way is to change the podspec file to match the native module. I'm not sure about the implications of doing that when autolinking though.
> 
> If possible, the library could ship two podspecs: the current one for auto-linking; and an alternative for manual link with the native name ReactNativeNotifications.podspec
> 
> Workaround while the library is not fixed:
> 
> Use [patch-package](https://www.npmjs.com/package/patch-package) to change the podspec file in node_module so it doesn't include package.json in the pod and also register the proper name.
> 
> After installing patch-package and adding it as postinstall, save this as patch file in `patches/react-native-notifications+3.1.4.patch`:
> 
> ```diff
> diff --git a/node_modules/react-native-notifications/react-native-notifications.podspec b/node_modules/react-native-notifications/react-native-notifications.podspec
> index c8e4e78..6db6a69 100644
> --- a/node_modules/react-native-notifications/react-native-notifications.podspec
> +++ b/node_modules/react-native-notifications/react-native-notifications.podspec
> @@ -3,7 +3,7 @@ require 'json'
>  package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
>  
>  Pod::Spec.new do |s|
> -  s.name           = 'react-native-notifications'
> +  s.name           = 'ReactNativeNotifications'
>    s.version        = package['version']
>    s.summary        = package['description']
>    s.description    = package['description']
> @@ -15,7 +15,7 @@ Pod::Spec.new do |s|
>    s.requires_arc   = true
>    s.platform       = :ios, '8.0'
>  
> -  s.preserve_paths = 'LICENSE', 'README.md', 'package.json', 'notification.ios.js', 'notification.android.js', 'index.android.js', 'index.ios.js'
> +  s.preserve_paths = 'LICENSE', 'README.md', 'notification.ios.js', 'notification.android.js', 'index.android.js', 'index.ios.js'
>    s.source_files   = 'lib/ios/*.{h,m}'
>  
>    s.dependency 'React'
> ```
> 
> Change `ios/Podfile` entry to:
> 
> ```
>   pod 'ReactNativeNotifications', :podspec => '../node_modules/react-native-notifications/react-native-notifications.podspec'
> ```
> 
> * Run `yarn install` and `cd ios && pod install`

Thanks!!! this worked a treat!

**Comment by DovletAmanov** [comment]
> pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'

worked for me too, thanks

**Comment by madandrija** [comment]
I have this issue when trying to use a fork of the repo - the repo doesn't contain `lib/dist` 😞  (which is included when retrieving the package from **npm**). Since there's no dist, it doesn't contain e.g. typescript definitions and the error message is totally valid (and the [proposed solution](https://github.com/wix/react-native-notifications/issues/557#issuecomment-624343937) doesn't work for this case). Not sure how to generate this, but noting it down in case someone else uses a fork and runs into the same problem.

**Comment by mkizesov** [comment]
@madandrija If you use a fork, you can build a dist folder using `npm run build`
Or you can run `npm pack` in the react-native-notifications folder. It will generates a tgz file which you can upload as a binary to release in your github repo.
More here https://glebbahmutov.com/blog/npm-install-with-just-github/ (just skip the part with adding `files` to package.json – it's not needed for this lib)
