### ISSUE TITLE
Register event is not always being called on iOS

### ISSUE THREAD

**Issue by StijnCoolen** [wix/react-native-notifications#558]
"react": "16.8.6"
 "react-native": "0.60.4"
"react-native-notifications": "^3.1.4"
Testing on physical device (iPhone 6s)

After testing I noticed that `Notifications.events().registerRemoteNotificationsRegistered` and/or it's native iOS counterpart `didRegisterForRemoteNotificationsWithDeviceToken` are not always called after   requesting and granting permission with `Notifications.registerRemoteNotifications()`;. Strange enough permission are actually set after granting but the event is not being called.

Sometimes restarting/re-installing the app on device works, but a couple of tries later it happens again.

The only possible explanation I can think of is that the events are not registered at the moment of calling `Notifications.registerRemoteNotifications()`, would this cause the observed behavior?

**Comment by danwhite-ipc** [comment]
I am having the same issue.

"react": "16.11.0",
"react-native": "0.62.2",
"react-native-notifications": "^3.1.4"

**Comment by bossajie** [comment]
Please help. Same issue

**Comment by danwhite-ipc** [comment]
You requesting permissions every time?

**Comment by saczuac** [comment]
Same issue now...

**Comment by chrisd1997** [comment]
Same issue here. Also tried setting the events in the `useState()` and calling the `Notifications.registerRemoteNotifications()` after button click, but no joy.

**Comment by monceeef** [comment]
Same here

**Comment by gabrielmoncea** [comment]
This issue is really important and needs to be verified. I've tried together with a colluage who has iOS experience and we couldn't figure it how to make it trigger the `registerRemoteNotificationsRegistered` callback and get the `deviceToken`. 

Even after a clean build, mac restart, `--reset-cache`, deleting `Pods` or `node_modules`.

Funny thing though, we are using `react-native-intercom` too and wanted to check if the Intercom notifications are still working. We tested our hypothesis and we received a notification and when the app opened, guess what... the callback was triggered and we received the `deviceToken`.

This makes me wonder what we did wrong and what we didn't do correctly. Intercom gets the `deviceToken` same way as `wix/react-native-notifications` does, but we can't figure it how it worked.

**Comment by gabrielmoncea** [comment]
I've managed to get the device token in a very hacky way.
I'm checking on every mount it's registered and if not I'm registering it again.

Let me know if it works for you too

```
  useEffect(() => {
    (async () => {
      const isRegistered = await Notifications.isRegisteredForRemoteNotifications();
      if (!isRegistered) Notifications.registerRemoteNotifications();
    })();
  });
```

**Comment by shawn-opslock** [comment]
Having the same issue.  I wonder if it's related to https://github.com/wix/react-native-notifications/issues/561

**Comment by yogevbd** [comment]
I tried to reproduce it in the example app with no luck.. Can you try listen to `RemoteNotificationsRegistrationFailed` event and print the response? It doesn't look related to the library itself.
```js
Notifications.events().registerRemoteNotificationsRegistrationFailed((event: RegistrationError) => {
    console.error(event);
});
```
