### ISSUE TITLE
How to set small icon for local notifications ?

### ISSUE THREAD

**Issue by ronastlelobo** [wix/react-native-notifications#654]

**Comment by berdimyradov** [comment]
Hello guys!

Decided to leave a comment here instead of creating a new issue.

So, currently I'm using [react-native-firebase v5](https://www.npmjs.com/package/react-native-firebase) which has support for notifications

However right now I'm trying to migrate to [react-native-firebase v6+](https://rnfirebase.io/) which does not have support for advanced notification features.
And setting icons to push-notification is one of them

Previously I used this type of code: 
```javascript
import { notifications } from 'react-native-firebase'

const notification = new notifications.Notification()
notification.android.setLargeIcon('setLargeIconUrlHere')
```

And now goes the question :)
Do you guys, support this feature? I was not able to find it in you documentations.

Thanks in advance 🙏

**Comment by JerakRus** [comment]
Hi! Did anyone manage to customize the icon? I get just a gray square

**Comment by ronastlelobo** [comment]
Follow this https://github.com/wix/react-native-notifications/issues/533#issuecomment-601513113

**Comment by JerakRus** [comment]
> Follow this [#533 (comment)](https://github.com/wix/react-native-notifications/issues/533#issuecomment-601513113)


Thanks a lot, it helped a lot!
