### ISSUE TITLE
when app state from running background to foreground, tap popup notification can't get notification detail

### ISSUE THREAD

**Issue by jackyang1984** [wix/react-native-notifications#739]
when app in dead status, tap notification, base on getInitialNotification can get notification detail, but when app from background to foreground, tap notification can't get notification detail, as the same time registerNotificationOpened never worked.

env: ios
react-native: 0.64.0
react-native-notifications: 3.4.2

**Comment by DanielEliraz** [comment]
It seems that this issue is duplicate of #561 .
Please check if andreialecu's [answer](https://github.com/wix/react-native-notifications/issues/561#issuecomment-824746532) is solving your bug too.

BTW, as the docs [says](http://wix.github.io/react-native-notifications/api/general-api#getinitialnotification) only when app is launched from the notification it is being returned in `getInitialNotification`.
