### ISSUE TITLE
Local Notification not working

### ISSUE THREAD

**Issue by felangga** [wix/react-native-notifications#77]
Hi, I'm using this library to test out the local notification on ios.
But it doesn't work, I already follow all the instructions.
Does it doesn't work on simulator ?

**Comment by jerbio** [comment]
I had the same problem but I later realized, the notifications were not showing because the application was in the foreground, this caused the  'notificationReceivedForeground' event to get fired.

You might want to put your call to 'NotificationsIOS.localNotification' in a [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout). This way you can switch to the home screen before the notification is sent.

**Comment by nolan-m** [comment]
I was able to get iOS local notifications by setting the `fireDate` to be a future time and minimizing the app, but Android does not have a `fireDate`.   I tried setTimeout, but that does not work because I believe the JS is frozen while the app is in the background.  The `NotificationsAndroid.setNotificationReceivedListener` does not fire when I send a local notification.    I see a log from my emulator console `D/ReactNativeNotifs: Native method invocation: postLocalNotification` which shows I did hit `postLocalNotification` in `RNNotificationsModule.java`, but the listener does not fire.

**Comment by cinder92** [comment]
same issue here...

**Comment by arunaiqvia** [comment]
Any fix?

**Comment by EarvinJay** [comment]
fireDate not working in android
