### ISSUE TITLE
not triggering when app is in kill state

### ISSUE THREAD

**Issue by AftabUfaq** [wix/react-native-notifications#784]
Notifications.events().registerNotificationOpened((notification, action) => {
      console.log(notification, action ,"notification, action")
    });

this function is calling when the application is in kill state.

**Comment by jvgeee** [comment]
@AftabUfaq Have you tried using `getInitialNotification` for this? https://wix.github.io/react-native-notifications/api/general-api#getinitialnotification

I think you're meant to use this method when the app mounts to see if it was kill => launched with a notification. 

If the app is closed and you're relying on `registerNotificationOpened`, it seems to me like your listeners won't be set up to actually receive the notification so this won't work. The Readme should probably be updated to reflect this, because I can't see it working when the app is in a "dead" state.

So I would do:

1. Initialise push notifications 
2. In a useEffect, register all your listeners so this happens on app launch
3. In the same useEffect, call `getInitialNotification`, which will check if there are any notifications in the queue to process

**Comment by uganof** [comment]
Hi I have the same problem but I use the getInittialialNotification function as suggested by @jvgeee

From various tests I have reached the following conclusions:

- the getInitialNotification function works fine on older versions of Android 11
- also works on android 11 in debug
- does not work on Android 11 in production
 
to reproduce the issue is simple:

1. on an android 11 emulator or an android 11 device send the production version with the usual command:
        npx react-native run-android --variant = release

2. return to the android home screen
3. kill the app with:
       adb shell am kill <your package>
4. send notify to app
5. tap on notify

The app opens and getInitialNotification return undefined.

**Comment by uganof** [comment]
Hi, I did further tests and discovered the following:

if you proceed in this way:

1. on an android 11 emulator or an android 11 device send the production version with the usual command:
       npx react-native run-android --variant = release

2. close the app with task manager 

3. send notify to app

4. tap on notify

5. the app opens and processes the notification correctly (getInitialNotification return notification object)

6. kill the app with:
      adb shell am kill your_package

7. send notify to app

8. tap on notify

9. the app opens and processes the notification correctly (getInitialNotification return notification object), 

from this moment on, even if the app is killed by the operating system, notifications are correctly processed!

obviously not good for an app, but it's a weird reaction that I can't understand, like it keeps a state in memory after closing the app and resurrecting following a notification

**Comment by uganof** [comment]
Last notice:

I created a test app in android studio directly in java and implemented the reception of notifications as per the firebase manual

The behavior is the same, so the problem is not in the react-native-notifications library but directly in the firebase library

if 
android:launchMode="singleTask" or "singleTop"

not work

if

android:launchMode="standard"

work

I think we can close the issue because it depends on google.

**Comment by claudiozam** [comment]
Hi, I have the same problem. @uganof do you have fix? Thanks

**Comment by viktor-CCM** [comment]
Hi, I have the same problem.  I used android:launchMode="standard" - doesn't work. 
@uganof do you have a fix?
@claudiozam  do you resolve the problem?

Notifications.getInitialNotification() return undefined when the application is in a kill state.
Thanks

**Comment by claudiozam** [comment]
@viktor-CCM i switched to https://rnfirebase.io and https://notifee.app (Android and IOS). No more problems for the moment. I love react-native-notifications but the show must go on.

![image](https://user-images.githubusercontent.com/2105644/197836450-dae2a13b-bf3a-422a-ad52-7e9d47e7d2f4.png)

**Comment by viktor-CCM** [comment]
> @viktor-CCM i switched to https://rnfirebase.io and https://notifee.app (Android and IOS). No more problems for the moment. I love react-native-notifications but the show must go on.
> 
> ![image](https://user-images.githubusercontent.com/2105644/197836450-dae2a13b-bf3a-422a-ad52-7e9d47e7d2f4.png)

@claudiozam Thanks.
