### ISSUE TITLE
Permanent crash with null notifications

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-notifications#83]
In some case, the notification that send to Emitter is null, so, the app will be crashed even after kill app completely. By the time the app restart, there's error "cannot read property "aps" of null" on
notification.ios.js:12:21

**Comment by Krayen** [comment]
Since this seems to be the same problem I'm having at the moment, I thought I'd post some info as well. Perhaps it can help someone figuring out what the issue is.

The process is as follows: ( in the iOS simulator )
1. Create a notification in my app by setting a firedate.
2. Close the app by pressing Cmd + Shift + HH and swiping it upwards. I.e not just minimizing it ( everything works in that case )
3. The notification appears as expected.
4. When I click it, it tries to start the app and this is the result:
![skarmavbild 2017-08-31 kl 17 11 05](https://user-images.githubusercontent.com/9949465/29930723-7fde4c00-8e6f-11e7-8c4c-38e68203a415.png)

and this is the output I get in Reactotron:
![skarmavbild 2017-08-31 kl 17 11 24](https://user-images.githubusercontent.com/9949465/29930755-937e4bb6-8e6f-11e7-9c9e-ccd16f9cdb9d.png)

**app.js**
```
class App extends React.Component {
  componentDidMount = () => {
    initNotifications()
  }

  render() {
    return (
      <Provider store={store}><AppNavigatorWithState /></Provider>
    )
  }
}

```

**initNotifications file**
```
export const initNotifications = () => {
  const snoozableMedicationCategory = new NotificationCategory({
    identifier: "SNOOZABLE_MEDICATION_CATEGORY",
    actions: [snoozeMedicationAction, takenMedicationAction],
  })

  const medicationCategory = new NotificationCategory({
    identifier: "MEDICATION_CATEGORY",
    actions: [takenMedicationAction],
  })

  NotificationsIOS.addEventListener('notificationReceivedForeground', onNotificationReceivedForeground)
  NotificationsIOS.addEventListener('notificationOpened', onNotificationOpened)

  NotificationsIOS.requestPermissions([snoozableMedicationCategory, medicationCategory])
  NotificationsIOS.consumeBackgroundQueue()
}

```

**Comment by DanAndreasson** [comment]
Any solution for this?

**Comment by davidstoker** [comment]
I ran into this same issue and series of steps described by @Krayen. See the referenced PR for a method for fixing.
