### ISSUE TITLE
OnClick on the notification takes to the starting page of the navigation.

### ISSUE THREAD

**Issue by Gowthamraj2399** [wix/react-native-notifications#846]
The navigation inside registerNotificationOpened event takes me to the initial page of the navigation stack.

Notifications.events().registerNotificationOpened(notification => {
      console.log('Notification opened by device user', notification.payload);
      RootNavigation.navigate('Chat');
});

**Comment by AftabUfaq** [comment]
any solution for this

**Comment by Epick362** [comment]
I think your issue stems from the fact that your initial navigator (possible some only for unauthorized users) does not contain the actual route you are trying to navigate to because it gets mounted after authentication happened. React-navigation threw an error in the packager so try to look for it.
